name: Java CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v1
      with:
        # Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: ${{ secrets.MY_PUB_PROFILE }}
        # Name of the Azure Web App
        app-name: freebergVueSpring
        # Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: target/*.jar
